### ISSUE TITLE
Bug: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by ambroiseRabier** [tdharmon/gatbsy-plugin-tslint#1]
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Cannot find module 'typescript'

File: src\pages\my-files.tsx

failed Building development bundle - 5.674s
```

Using this plugin with `gatsby-plugin-typescript` plugin. Is it not compatible?

There is no instruction saying I should install Typescript, also it says: "Provides drop-in support for TSLint."

I am using it wrong?

**Comment by thetrevorharmon** [comment]
@ambroiseRabier what does your `package.json` look like? Both this plugin and `gatsby-plugin-typescript` provide typescript support with Gatsby, but neither actually include it. You need to install typescript separately.

**Comment by ambroiseRabier** [comment]
Ok. If peoples need to install typescript separately, it should be in the instructions. Also, having a separate Typescript for linting and transpiling seem weird.
